### ISSUE TITLE
PyGIWarning: GConf was imported without specifying a version first.

### ISSUE THREAD

**Issue by Jumblemuddle** [projecthamster/hamster#287]
configuration.py:33: PyGIWarning: GConf was imported without specifying a version first. Use gi.require_version('GConf', '2.0') before import to ensure that the right version gets loaded.
from gi.repository import GConf as gconf

I get this message whenever I run hamster. I've tried doing what it suggested, however my package manager doesn't have a gconf 2.0 package. (Void linux)
Any idea how I could suppress this message?

For completeness sake:
![hamster](https://cloud.githubusercontent.com/assets/3629343/12990139/54f7d2f0-d0ce-11e5-9b3d-09919920e2b3.png)

**Comment by bzimage-it** [comment]
I get same error too. I just made "dnf update" on my Fedora 24 and the issue appears.
I also tried to build hamster from source (git clone master right now) and i get the same problem running /usr/local/bin/hamster.

attached files:
[sebastiani@pcfaber ~]$ /usr/local/bin/hamster > output.txt 2>&1 
[sebastiani@pcfaber ~]$ rpm -qa|sort > rpm-qa.list.txt

[info-issue-287.zip](https://github.com/projecthamster/hamster/files/134494/info-issue-287.zip)

**Comment by FelixSchwarz** [comment]
This problem is usually harmless just about annoying log spam. Parts of it were fixed in 03546fd08d4ef88b75f12430940b1c9bd9ac18b2.

**Comment by bzimage-it** [comment]
Not really. I tried the patch, but issues still happens. I discover that the real problem is wide and seems that current hamster version has issues with recent fedora 23 updates.
See here: https://bugzilla.redhat.com/show_bug.cgi?id=1307253
While waiting for the fix, I solved the problem downgrading the package "sudo dnf downgrade hamster-time-tracker", as suggested in comment `#4`.

**Comment by kaizoku** [comment]
I created https://github.com/projecthamster/hamster/pull/353 which fixes these warnings on my machine.

**Comment by elbenfreund** [comment]
Thank you for your feedback, it is much appreciated.

Project hamster and its various sub-components is currently undergoing some major changes. We prepare the introduction of a rewritten codebase for most of the underlying functionality. A direct consequence of this is that it is unlikely that any open/new bugs within the current/old codebase will be fixed (unless someone steps up and offers to do so) as most resources currently available will be invested in making the rewrite prime time ready.

**Comment by ederag** [comment]
This should be fixed in [v2.1.1](https://github.com/projecthamster/hamster/releases/tag/v2.1.1)
Thanks for the report, and thanks to @kaizoku for providing a fix.
