### ISSUE TITLE
Activities text too small on HiDPI screens

### ISSUE THREAD

**Issue by AdrianSimionov** [projecthamster/hamster#312]
Activities tab has the text too small, it does not seem to respect the DPI of the system.

![march 27 april 02 2016_630](https://cloud.githubusercontent.com/assets/6671693/14071655/f48d00ee-f502-11e5-926b-7ac024f68922.png)

**Comment by karolszk** [comment]
Hello, I also confirm that on Debian Stretch on resolution 2560x1440 (16:9) activities are too small. See my screenshot.

**Comment by chri2** [comment]
Changed it for totals on my system for the same reason: HiDPI. Look [here](https://github.com/projecthamster/hamster/issues/289). Maybe it helps to change this tab also...

**Comment by elbenfreund** [comment]
Thank you for your feedback, it is much appreciated.

Project hamster and its various sub-components is currently undergoing some major changes. We prepare the introduction of a rewritten codebase for most of the underlying functionality. A direct consequence of this is that it is unlikely that any open/new bugs within the current/old codebase will be fixed (unless someone steps up and offers to do so) as most resources currently available will be invested in making the rewrite prime time ready.

**Comment by ederag** [comment]
Thanks for the reports.
This issue seems related to the old hamster-applet (1.0.4 ?)
This seems fixed now, probably thanks to the v2 gtk3 migration
(tested on openSUSE Leap-15, 2560x1440, [v2.1.1](https://github.com/projecthamster/hamster/releases/tag/v2.1.1))

**Comment by GeraldJansen** [comment]
Not sure if this is the same problem, but even with current master on XFCE, some fonts reflect the custom DPI settings and others do not.
![Screenshot_2019-08-11_16-29-00](https://user-images.githubusercontent.com/31414956/62835225-06467180-bc56-11e9-85de-f9d3a412be1f.png)

**Comment by ederag** [comment]
Fixed by @GeraldJansen in PR #426, thanks !
Leaving open, but with the `hamster-applet` label, since it is still an issue in version 1.

**Comment by GeraldJansen** [comment]
I feel that we should close issues in hamster-applet that have been fixed in current hamster master, after providing a kindly explanation. That software is now ancient and realistically no-one is ever going to work on it again. Excessive open issues give the impression that the software is buggier and less complete than it actually is. Personally I find it demotivating to fix an issue and not see it closed. 
(Btw, I guess #289 is the same issue)

**Comment by ederag** [comment]
I hear you, thanks for sharing your thoughts.
Changing the meaning of `hamster-applet` label from "fixed in v2" to
"issue still there in versions < v2 and in v2.91.3"
This way we can close issues while keeping track of the progress between v1 and v2.
