### ISSUE TITLE
Weird display of dark grey lines when filtering activities

### ISSUE THREAD

**Issue by u451f** [projecthamster/hamster#636]
tags: UX, enhancement

When I filter my activities, it looks like other activities are shown as dark grey lines.
See screenshot below:
![Bildschirmfoto von 2020-10-20 17-58-24](https://user-images.githubusercontent.com/6314248/96612301-e3a1f500-12fd-11eb-92f0-9e8ef18f9167.png)

I find that this makes it a bit hard to read my screen, and see what I really did do. It also makes the scroll bar on the right extremely long.

**Comment by u451f** [comment]
Oh, this was already fixed, see #615

**Comment by matthijskooijman** [comment]
Nope, wasn't fixed yet (but is about to), so I'll reopen this for just a little bit :-)
